export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOAD_ADMINS_SUCCESS = 'LOAD_ADMINS_SUCCESS';

export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';

export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';

export const LOAD_INSTITUTIONS_SUCCESS = 'LOAD_INSTITUTIONS_SUCCESS';
export const DELETE_INSTITUTION_SUCCESS = 'DELETE_INSTITUTION_SUCCESS';
export const CREATE_INSTITUTION_SUCCESS = 'CREATE_INSTITUTION_SUCCESS';
export const UPDATE_INSTITUTION_SUCCESS = 'UPDATE_INSTITUTION_SUCCESS';


export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';

export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const CREATE_ROUTE_SUCCESS = 'CREATE_ROUTE_SUCCESS';

export const DELETE_ROUTE_SUCCESS = 'DELETE_ROUTE_SUCCESS';
