export const CREATE_INSTITUTION = 'CREATE_INSTITUTION';


export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOAD_ADMINS = 'LOAD_ADMINS';
export const LOAD_ADMINS_SUCCESS = 'LOAD_ADMINS_SUCCESS';
export const LOAD_ADMIN = 'LOAD_ADMIN';

export const CREATE_ADMIN = 'CREATE_ADMIN';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';

export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';

export const LOAD_INSTITUTIONS_SUCCESS = 'LOAD_INSTITUTIONS_SUCCESS';
export const DELETE_INSTITUTION_SUCCESS = 'DELETE_INSTITUTION_SUCCESS';
export const CREATE_INSTITUTION_SUCCESS = 'CREATE_INSTITUTION_SUCCESS';
export const UPDATE_INSTITUTION_SUCCESS = 'UPDATE_INSTITUTION_SUCCESS';


export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
